#include <relop.h>
#include <atomic.h>

ATOMIC_BEGIN(Eq, =, B(x == y))
    ATOMIC1(B); ATOMIC1(C); ATOMIC1(D); ATOMIC1(F); ATOMIC1(H); ATOMIC1(I);
    ATOMIC1(J); ATOMIC1(S); ATOMIC1(T); ATOMIC1(X);
    ATOMICOO();
ATOMIC_END(eq)

ATOMIC_BEGIN(Less, <, B(x < y))
    ATOMIC1(B); ATOMIC1(C); ATOMIC1(D); ATOMIC1(F); ATOMIC1(H); ATOMIC1(I);
    ATOMIC1(J); ATOMIC1(S); ATOMIC1(T); ATOMIC1(X);
    ATOMICOO();
ATOMIC_END(less)

ATOMIC_BEGIN(Greater, >, B(x > y))
    ATOMIC1(B); ATOMIC1(C); ATOMIC1(D); ATOMIC1(F); ATOMIC1(H); ATOMIC1(I);
    ATOMIC1(J); ATOMIC1(S); ATOMIC1(T); ATOMIC1(X);
    ATOMICOO();
ATOMIC_END(greater)

ATOMIC_BEGIN(Max, |, x<y?y:x) // cppcheck-suppress syntaxError
    ATOMIC1(B); ATOMIC1(C); ATOMIC1(D); ATOMIC1(F); ATOMIC1(H); ATOMIC1(I);
    ATOMIC1(J); ATOMIC1(S); ATOMIC1(T); ATOMIC1(X);
    ATOMICOO();
ATOMIC_END(max)

ATOMIC_BEGIN(Min, &, x<y?x:y)
    ATOMIC1(B); ATOMIC1(C); ATOMIC1(D); ATOMIC1(F); ATOMIC1(H); ATOMIC1(I);
    ATOMIC1(J); ATOMIC1(S); ATOMIC1(T); ATOMIC1(X);
    ATOMICOO();
ATOMIC_END(min)
