name: on-push
on: [push]
jobs:
  linux-debug-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
             sudo apt update
             sudo apt install gcc-10 g++-10
      - run: |
             cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -S . -B build
             cmake --build build
             build/utest
  macos-debug-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
             cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
             cmake --build build
             build/utest
